@baseUrl = http://localhost:3333
@contentType = application/json


### Create Class

POST {{baseUrl}}/classes
Content-Type: {{contentType}}

{
  "name": "Lucas",
  "avatar": "https://media-exp1.licdn.com/dms/image/C4E03AQF-HBkvKkQU_A/profile-displayphoto-shrink_200_200/0?e=1602115200&v=beta&t=q59UONWa6j8IE1uowpiNPM4JLNG4XEMKOpcC9u7-Sy4",
  "whatsapp": "48991224064",
  "bio": "A good teacher from Florianopolis.",
  "subject": "Chemistry",
  "cost": 60,
  "schedule": [
    {
      "week_day": 1,
      "from": "8:00",
      "to": "12:00"
    },
    {
      "week_day": 3,
      "from": "10:00",
      "to": "16:00"
    },
    {
      "week_day": 4,
      "from": "8:00",
      "to": "12:00"
    }
  ]
}

### List Classes

GET {{baseUrl}}/classes?week_day=1&subject=Chemistry&time=11:00
Content-Type: {{contentType}}

### Create Connection

POST {{baseUrl}}/connections
Content-Type: {{contentType}}

{
  "user_id": 1
}

### Count Connections

GET {{baseUrl}}/connections
Content-Type: {{contentType}}

